version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    cooldown:
      days-from-release: 14
    groups:
      prisma:
        patterns:
          - '*prisma*'
      types:
        patterns:
          - '@types/*'
