/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Side {
  Buy = 0,
  Sell = 1
}
export interface LimitOrder {
  tick: number
  amount: bigint
}
export interface SwapInput {
  amount: bigint
  limitOrders: Array<LimitOrder>
  poolFee?: number
  side: Side
}
export interface SwapOutput {
  swappedAmount: bigint
  remainingAmount: bigint
}
export function findPrice(args: SwapInput): Promise<SwapOutput>
