/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LimitOrder {
  tick: number
  amount: bigint
}
export interface SwapInput {
  amount: bigint
  limitOrders: Array<LimitOrder>
  poolFee?: number
}
export interface SwapOutput {
  swappedAmount: bigint
  remainingAmount: bigint
}
export function findPrice(args: SwapInput): Promise<SwapOutput>
