/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LimitOrder {
  tick: number
  amount: bigint
}
export interface Args {
  amount: bigint
  limitOrders: Array<LimitOrder>
  poolFee?: number
}
export interface Output {
  swappedAmount: bigint
  remainingAmount: bigint
}
export function findPrice(args: Args): Promise<Output>
