export default {
  RPC_NODE_HTTP_URL: 'http://rpc-node.test',
  START_HTTP_SERVICE: false,
  START_PROCESSOR: false,
  SWAPPING_APP_PORT: 8080,
  BITCOIN_DEPOSIT_TRACKER_URL: '',
  RPC_BROKER_HTTPS_URL: 'https://rpc-broker.test',
  RPC_NODE_WSS_URL: 'ws://rpc-node.test',
  CHAINFLIP_NETWORK: 'perseverance',
  QUOTE_TIMEOUT: 1000,
  NODE_ENV: 'test',
  CHAINALYSIS_API_KEY: undefined,
  INGEST_GATEWAY_URL: 'https://ingest-gateway.test',
  PROCESSOR_BATCH_SIZE: 50,
  PROCESSOR_TRANSACTION_TIMEOUT: 10_000,
  REDIS_URL: 'redis://localhost:6379',
  MAINTENANCE_MODE: false,
  DISABLED_INTERNAL_ASSETS: [],
  MAX_CHANNELS_OPEN_PER_ADDRESS: 10,
  DISABLE_QUOTING: false,
  SOLANA_RPC_HTTP_URL: 'http://solana-rpc.test',
  STABLE_COIN_SLIPPAGE_MIN_PRICE: 0.995,
};
